name: pocket_bussiness_solution
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.14.0+5
  provider:
  cloud_firestore:
  toast:
  charts_flutter: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
   - assets/images/74-512.png
   - assets/images/avatar.png
   - assets/images/avatar-2.png
   - assets/images/avatar-3.png
   - assets/images/avatar-4.png
   - assets/images/avatar-5.png
   - assets/images/avatar-6.png
   - assets/images/avatar-7.png
   - assets/images/avatar-8.png
   - assets/images/avatar-9.png
   - assets/images/avatar-10.png
   - assets/images/avatar-11.png
   - assets/images/bg-white-gray.png
   - assets/images/box-new-used-gaylord-boxes-for-sale-reliable-industries-llc-22.png
   - assets/images/bulk-order-icon-1.png
   - assets/images/cencel-icon.png
   - assets/images/ellipse-1.png
   - assets/images/ellipse-2.png
   - assets/images/ellipse-3.png
   - assets/images/fabrica-cajas-4.png
   - assets/images/finance_screen.png
   - assets/images/financial-icon-png-buy-this-icon-for--0-48-2.png
   - assets/images/gradient.png
   - assets/images/gradient-2.png
   - assets/images/group-4.png
   - assets/images/group-4-2.png
   - assets/images/group-4-3.png
   - assets/images/group-4-4.png
   - assets/images/group-4-5.png
   - assets/images/group-4-6.png
   - assets/images/group-4-7.png
   - assets/images/group-4-8.png
   - assets/images/group-4-9.png
   - assets/images/group-4-10.png
   - assets/images/group-4-11.png
   - assets/images/group-4-12.png
   - assets/images/group-4-13.png
   - assets/images/group-5.png
   - assets/images/group-5-2.png
   - assets/images/group-5-3.png
   - assets/images/group-6.png
   - assets/images/group-6-2.png
   - assets/images/group-49.png
   - assets/images/ico.png
   - assets/images/icons8-attendance-100.png
   - assets/images/icons8-human-resources-100-1.png
   - assets/images/icons8-sales-performance-100.png
   - assets/images/icons-x.png
   - assets/images/image.png
   - assets/images/jerene-march-2016-hris-shutterstock-700x420.png
   - assets/images/line.png
   - assets/images/line-1.png
   - assets/images/logo.png
   - assets/images/logo-2.png
   - assets/images/logo-3.png
   - assets/images/logo-4.png
   - assets/images/mz_logo.png
   - assets/images/notifications.png
   - assets/images/part.png
   - assets/images/part-2.png
   - assets/images/part-3.png
   - assets/images/path-3.png
   - assets/images/photo.png
   - assets/images/photo-2.png
   - assets/images/photo-3.png
   - assets/images/report-online-business-reporting-512.png
   - assets/images/report_screen.png
   - assets/images/sales_sheet.png
   - assets/images/shape.png
   - assets/images/shape-2.png
   - assets/images/shape-3.png
   - assets/images/shape-4.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
